<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/4
 * Time: 21:10
 */

namespace backend\filters;


use yii\base\ActionFilter;
use yii\web\HttpException;

class CheckFilter extends ActionFilter
{
    public function beforeAction($action)
    {
        if(!\Yii::$app->user->can($action->uniqueId)){
            throw new HttpException(403,'你没有权限，快滚！！');
//            $html=<<<HTML
//        22222222
//HTML;
//
//            echo $html;return false;
        }


        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


}